@url = "http://localhost:4000/"

GET http://localhost:4000/ HTTP/1.1

###
GET http://localhost:4000/resCheck HTTP/1.1


###
POST http://localhost:4000/createUser HTTP/1.1
Content-Type: application/json
{
    "realName":"hemlo boi",
    "userName":"neel",
    "email":"helmo@gmail.com",
    "image":"imagephotobekar",
    "walletAddress":"29834u209x9zxz8989xz8"

}
###
POST http://localhost:4000/cUser HTTP/1.1
Content-Type: image/png
Content-Disposition: form-data; name="image"; filename="1.png"

< ./money.png
